repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix, --config, .pre-commit/ruff.toml]
      - id: ruff-format
        args: [--config, .pre-commit/ruff.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        # Run mypy with our config over specific targets; don't pass filenames
        args: [--python-version=3.11, --config-file, .pre-commit/mypy.ini, app, scripts, tests]
        pass_filenames: false
        additional_dependencies:
          - pydantic>=2
          - sqlalchemy>=2

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        # Run Bandit recursively on app/ and scripts/ only
        args: [-q, -r, app, scripts, -x, tests]
        # Don't pass changed filenames; rely on the explicit args above
        pass_filenames: false

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .pre-commit/.secrets.baseline, --exclude-files, "^\\.pre-commit/\\.secrets\\.baseline$"]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        exclude: ^uv\.lock$
      - id: check-json
      - id: check-yaml
      - id: check-toml
