site_name: Narada Docs
repo_url: https://example.com
docs_dir: .
nav:
  - Overview: index.md
  - Architecture:
      - Overview: architecture/overview.md
  - API:
      - Design: api/design.md
  - Data Model:
      - Overview: data-model/overview.md
  - Ingestion & Pipelines:
      - Pipelines: ingestion/pipelines.md
  - RAG:
      - Chroma Store: rag/chroma.md
  - Product:
      - Feedback Loop: product/feedback-loop.md
  - Operations:
      - Taskfile: ops/taskfile.md
      - Migrations: ops/migrations.md
  - Development:
      - Conventions: dev/conventions.md
      - Testing: dev/testing.md
theme:
  name: mkdocs
